### ISSUE TITLE
gcc arch linux x86_64 pulled from branch asm

### ISSUE THREAD

**Issue by shios86** [RaphaelBadia/Corewar#4]
src/label.c: In function ‘get_label_to_find’:
src/label.c:105:3: warning: implicit declaration of function ‘ft_addlabelline’ [-Wimplicit-function-declaration]
   ft_addlabelline(data->to_fill, data);

**Comment by vcombey** [comment]
Fixed

**Comment by raphaelbadia** [comment]
Fixed.
