### ISSUE TITLE
compiled with gcc -Wall -Wextra -pedantic, checked leaks using valgrind valgrind-3.12.0

### ISSUE THREAD

**Issue by shios86** [RaphaelBadia/Corewar#6]
==980== 17 bytes in 1 blocks are definitely lost in loss record 1 of 1
==980==    at 0x4C2AB8D: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==980==    by 0x408275: ft_strnew (ft_strnew.c:20)
==980==    by 0x40088B: create_cor (main.c:88)
==980==    by 0x400B17: main (main.c:142)

**Comment by vcombey** [comment]
done
